### ISSUE TITLE
オプションの案が欲しいです

### ISSUE THREAD

**Issue by tanacchi** [tanacchi/mbed_PBL#1]
明るい方を向くみたいな機能はサイズとかの関係で無理そうでした。
じゃけえ代案を考えていただきたいです

今のところ、モード選択で「温度計」と「カウンター」の機能を取り入れようかなっていう案しか出てないです
できるだけ多くの案がほしいっていうのと、開発にかかる時間を考えるとなるべく早く決定したいっていう感じです

よろしくお願いします〜

**Comment by tanacchi** [comment]
今のところボタン二個
もう一個追加出来ればスロット出来そう

**Comment by yancygorigori** [comment]
タイマーとかどうですかね
小数点第1位まで表示にして

**Comment by tanacchi** [comment]
@yancygorigori ゴリゴリさんありがとう！参考にするっぺよ

**Comment by yancygorigori** [comment]
@tanacchi 呼び方な（ー＿ー）

**Comment by tanacchi** [comment]
照度センサーを使って、暗いところでは数値を見やすいように７せぐ周りに取り付けたLEDを光らせるというのはどげ？
今購入してある部品で作れるべ
byたむちん

**Comment by yancygorigori** [comment]
@tanacchi ナイスうほーー！！

**Comment by tanacchi** [comment]
出た案の中でいけそうなのから頑張ってみます
ありがとうございました〜
