### ISSUE TITLE
 J班のプログラミングについて

### ISSUE THREAD

**Issue by sakimatsuura** [tanacchi/mbed_PBL#5]
何となくは分かるんだけど発表の時説明できるか分からないので、J班の分のキッチンタイマーのプログラミングの説明をざっくりでもいいからまた文章で流れを説明してもらったりできませんか?

```C++
void sevseg_LED::split_Numerical_Pos() {
  int i, j, k = 0;
  for (i = head; i > tale; i--){
    for (j = 0; input_number >= powpow(10, i); j++) input_number -= powpow(10, i);
    splited_num[k++] = j;
  }
}
```

```C++
void sevseg_LED::input_inteder_ary() {
  for (int i = 0; i < SEVSEG_WIDTH; i++)
    for (int j = 0; j < SEGMENT_NUM; j++)
      inteder_array[i][j] = convert_NUMintoARY(splited_num[i])[j];
}
```

```C++
void sevseg_LED::output_sevseg() {
  output_array(inteder_array);
}
```

```C++
int powpow(int a, int b) {
  int dest = 1;
  if (b > 0) for (int i = 0; i < b; i++) dest *= a;
  if (b < 0) for (int i = 0; i > b; i--) dest /= a;
  return dest;
}
```

あとここらへんがあまりピンとこなかったので説明してもらえたらうれしいです
できたら文章だと見返せるからそっちのほうがありがたいです

あと、スイッチとブザーは講義資料のをそのまま入れればいいよね?どこに入れるかが今まだ分からないんだけど

長くなってごめんね、よかったらお願いします

**Comment by sakimatsuura** [comment]
ごめん！やっぱ見たらGitHubのたなっちの説明見たら分かりそう
if (count == 1) param--;
ここだけどういうことか聞いていい?

**Comment by sakimatsuura** [comment]
あ、あとスイッチとブザーのプログラム入れる位置お願いします

**Comment by tanacchi** [comment]
```C++
if (count == 1) param--;
```

これはcount という変数が1 ならparam を１減らすという意味です

**Comment by tanacchi** [comment]
73行目のところ

```C++
void sevseg_Clock() {
  static int data = 180;
  sevseg_LED time(3);
  while (1){
    data = get_time(data);
    get_time(data);
    time.set_number(data);
    time.split_Numerical_Pos();
    time.input_inteder_ary();
    time.output_sevseg();
  }
}
```

の部分を、

```C++
void sevseg_Clock() {
  static int data = 180;
  sevseg_LED time(3);
  while (1){
  
    if (data < 0) {
    //  ブザーを鳴らす記述 //
    }

    data = get_time(data);
    get_time(data);
    time.set_number(data);
    time.split_Numerical_Pos();
    time.input_inteder_ary();
    time.output_sevseg();
  }
}
```

にすればいい感じのタイミングでブザーがなると思います

**Comment by tanacchi** [comment]
ごめん何に使うスイッチやったっけ？？

**Comment by tanacchi** [comment]
スイッチの位置についてはまたあとで言います

**Comment by sakimatsuura** [comment]
時計のプログラミングの70行目のstruct tm tm;と71行目ってどういうことだっけ？
あともしこっちの班のプログラミング見れたらでいいんだけど、107行目から128行目までのところって、桁を一つずつ見てどうするとこだったかな？
あとキッチンタイマーのところで、なにを500回繰り返したら７セグの数字を1引くのかのループ、500回繰り返しすところはどこかと、表示までの流れをまた教えてほしいです
GitHubの説明をくれてるページの表示する数値を桁ごとに分割する関数の中身と、タイマーのプログラミングの99～103行目が結局何のための操作かわかんなくなっちゃったので教えてほしいです。

聞くの遅くなってごめんね！よろしくお願いします。

**Comment by sakimatsuura** [comment]
この前聞いたとこの桁ごとに数値を分割す関数についてはそっちの班で説明する？
そこ説明するならこっちではそこは省略するからわかんなくても最悪大丈夫です。

**Comment by tanacchi** [comment]
１個ずつ解決していきますー
①
>時計のプログラミングの70行目のstruct tm tm;と71行目ってどういうことだっけ？

ここは俺が書いたやつやないけはっきりとは言えんけど
（ｔｍ型構造体とtime_t型の変数を定義して）
時刻データを格納するための変数を用意してるみたいです

**Comment by tanacchi** [comment]
②
>107行目から128行目までのところって、桁を一つずつ見てどうするとこだったかな？

まず１０７〜１１９行目
```C++
void sevseg_LED::split_Numerical_Pos(){
  int i, j, k = 0;
  for (i = head; i > tale; i--){
    for (j = 0; input_number >= powpow(10, i); j++) input_number -= powpow(10, i);
    splited_num[k++] = j;
  }
}
```
Ｊさんに合わせて説明すると、headが３に設定されてるので
数値データ(ｉｎｐｕｔ_number)から１０の３乗が何回引けるかを数えます
１０３２なら一回引けます
> for (j = 0; input_number >= powpow(10, i); j++) input_number -= powpow(10, i);

①最初にｊを０に設定して
②ｉｎｐｕｔ_ｎｕｍｂｅｒ>= powpow(10, 3) ←１０００なら続行
③ｉｎｐｕｔ_ｎｕｍｂｅｒからpowpow(10,3)を引きｊに１を足す

②③を繰り返してたらいつかｉｎｐｕｔ_ｎｕｍｂｅｒ>= powpow(10, 3)を満たさなくなります
そのときのｊの値が＂何回引けたか＂になります

これらを１０の３乗から１０の０乗まで順に実行すると
数値が１０３２だったら

１０の３乗　＞＞　１回
１０の２乗　＞＞　０回
１０の１乗　＞＞　３回
１０の０乗　＞＞　２回
となって
それぞれの位の数を導けます

**Comment by tanacchi** [comment]
１１５〜１１９行目
```C++
void sevseg_LED::input_inteder_ary(){
  for (int i = 0; i < SEVSEG_WIDTH; i++)
    for (int j = 0; j < SEGMENT_NUM; j++)
      output_array[i][j] = exchange_NUMtoARY(splited_num[i])[j];
}
```
さきほどのそれぞれの位の数に対応するＯＮ/OFFの並びを取得します

０なら最後だけＯＦＦでそれ以外ＯＮ
８なら全部ＯＮ

なので

exchange_NUMtoARY(８])[０]　＝　ＯＮ
exchange_NUMtoARY(８)[１]　＝　ＯＮ
exchange_NUMtoARY(８)[２]　＝　ＯＮ
　　　　　　：
exchange_NUMtoARY(８)[６]　＝　ＯＮ


それらを格納するための３行７列の二次元配列（行列っぽいの）
を用意して（ｏｕｔｐｕｔ＿ａｒｒａｙ［ｉ］［ｊ］）

i は何桁目の数字か
ｊは何番目のＯＮ・ＯＦＦかを示していて
i = 0で最頭の桁から
>for (int j = 0; j < SEGMENT_NUM; j++)

でセグメントの数（＝７）だけ繰り返しながら
１個ずつＯＮ・ＯＦＦを代入していきます

ひと桁分終わったら次の桁へって感じです

**Comment by tanacchi** [comment]
１２１〜１２８行目まで
```C++
void sevseg_LED::output_sevseg(){ 
  for (int i = 0; i < SEVSEG_WIDTH; i++){
    digits_init();
    digit[i] = 0;　　
    output_digit(output_array[i]);
    wait(0.001);
  }
}
```

さっきの3x7の配列を７セグに対応させる

>for (int i = 0; i < SEVSEG_WIDTH; i++)

桁の数だけ繰り返す（）４回

>    digits_init();
>    digit[i] = 0;

一回全部の桁の電流をシャットアウトして
表示したい桁だけ電流が流れるようにする

>output_digit(output_array[i]);

ひとけた分のＯＮ／ＯＦＦの並びをａ～ｇに代入してひとけただけ表示
あと一瞬だけｗａｉｔを置く

これを４桁分繰り返す

**Comment by tanacchi** [comment]
③

>キッチンタイマーのところで、なにを500回繰り返したら７セグの数字を1引くのかのループ、500回繰り返しすところはどこかと、表示までの流れ

繰り返しているのは
sevseg_Clock()内のwhile(1)の中です

```C++
void sevseg_Clock() {
  static int data = 15;
  sevseg_LED time(3);
  
  while (mysw == 0) ;
  
  while (1){        　　　　　　　　　 // ここから
    
    if(data <= 0)
    {
     mysp1.period(1.0/391.995);
     mysp1.write(0.5);
     wait(1);   
     if (mysw == 1) break;
    }
    data = get_time(data);
    get_time(data);
    time.set_number(data);
    time.split_Numerical_Pos();
    time.input_inteder_ary();
    time.output_sevseg();
  }　　　　　　　　　　　　　　　　　// ここまで
}
```

繰り返すたびに
>  data = get_time(data);

のところでget_time関数を実行します（下の get_time(data);はいらないです）

```C++
int get_time(int param) {
  static int count;
  if (++count > 500) count = 0;
  if (count == 1) param--;
  return param;
}
```
そしてget_time関数を実行するたびにint型変数countを加算していってます

**繰り返しているのはsevseg_Clock関数内のwhile（１）の中括弧の中、
加算するタイミングはその中のget_timeを実行する時**


```C++
void sevseg_Clock() {
　　　　：
　　　　：
    data = get_time(data);         //数値データの操作
    get_time(data);                // いらない
    time.set_number(data);           // 表示する用にデータを設定
    time.split_Numerical_Pos();      // 桁ごとに分割
    time.input_inteder_ary();        // 3x7の配列を生成
    time.output_sevseg();         // 配列を７セグに対応するように光らせる
  }　　　　　　　　　　　　
}
```

そっからの流れはこんな感じ↑

**Comment by sakimatsuura** [comment]
なるほど！ありがとう！

**Comment by tanacchi** [comment]
④
>表示する数値を桁ごとに分割する関数の中身と、タイマーのプログラミングの99～103行目が結局何のための操作か

７セグＬＥＤが、もともとは”指定したＬＥＤを光らせる”という機能のみを持っているもので
人間がそれを数字として認識させるには
数字ごとに”どこを光らせればよいのか”を命令する必要があります

また今回扱う７セグＬＥＤはダイナミック点灯方式を採用しており、
桁ごとに違う数字を一度に表示させることが出来ません

ひと桁ずつ表示させ、
さらに表示する桁を高速で切り替えることで
人間目線では
桁ごとに違う数字が
同時に点灯しているように見えます

```C++
void sevseg_LED::output_sevseg(){ 
  for (int i = 0; i < SEVSEG_WIDTH; i++){
    digits_init();
    digit[i] = 0;　　
    output_digit(output_array[i]);
    wait(0.001);
  }
}
```

↑この辺がそれを実現させるための操作です

```C++
int get_time(int param) {
  static int count;
  if (++count > 500) count = 0;
  if (count == 1) param--;
  return param;
}
```
タイマーのプログラミングっていうのはここのことかな？

ループするのにも僅かながら時間がかかっていて
それを５００回くらい繰り返したら１秒になるかなって感じ
500回実行して一回だけ数字を下げるっていう風にすると
一定の間隔を置いて数字を下げていく感じになります

```C++
   data = get_time(data); 
```

もともとget_time関数は引数（括弧の部分）に数値（ｄａｔａ）を入れて
５００回に一回だけ
それより１小さい値を返す関数であって、
上の記述だと５００回に一回、１小さい値がdataに代入されています

それ以外の時はそのままの値を返して
上の記述だとそのままのあたいをdataに代入していています（ｄａｔａ自体に変化はない）

**Comment by tanacchi** [comment]
⑤
>この前聞いたとこの桁ごとに数値を分割す関数についてはそっちの班で説明する？

します
ざっくりだけど

普通はこんなん聞いても誰も理解出来んよｗ

**Comment by tanacchi** [comment]
お疲れ様でした〜
やんしー焼き肉ごちでぇす
